apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - ingress.yml
  - secret.yml
replacements:
  - source:
      kind: Secret
      name: flowix-website-secret
    targets:
      - select:
          kind: Deployment
          name: flowix-website
        fieldPaths:
          - spec.template.spec.containers.[name=app].[image=APP_IMAGE]
#vars:
#  - name: APP_URL
#    objref:
#      kind: Secret
#      name: flowix-website-secret
#
#  - name: REGISTRY_URL
#    objref:
#      kind: Secret
#      name: flowix-website-secret